# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Clue-less Pylint

on:
  push:
    branches: [ "*" ]  # This will trigger the workflow on every branch
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.12"
        environment-file: clue_env_release.yml  # Use your environment file here
        environment-name: clue_env
    - name: Install dependencies
      run: |
        conda init bash  # Initialize Conda for bash
        source ~/.bashrc  # Source the bash configuration
        conda env list
        conda activate test  # Activate your custom Conda environment
        conda install flake8 pytest  # Install flake8 and pytest using conda
    - name: Lint with flak8
      run: |
        conda init bash  # Initialize Conda for bash
        source ~/.bashrc  # Source the bash configuration
        conda activate test  # Activate your custom Conda environment
        flake8_output=$(flake8 .)  # Capture the flake8 output
        echo "$flake8_output"  # Print the flake8 output
        error_count=$(echo "$flake8_output" | wc -l)  # Count the number of lines (errors)
        if [ "$error_count" -ne 0 ]; then
          score=$((100 - error_count))  # Calculate the score
          echo "Score: $score"  # Display the score
        else
          echo "Score: 100 - No errors!"  # Perfect score
        fi
#    - name: Test with pytest
#      run: |
#        pytest